apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: sorting-algorithms-dev

images:
  - name: usamaahmed99/sorting-algorithms
    newName: usamaahmed99/sorting-algorithms
    newTag: latest

patches:
  - path: patch-service.yaml
