apiVersion: v1
kind: Service
metadata:
  name: sorting-algorithms-service
spec:
  type: ClusterIP
  selector:
    app: sorting-algorithms
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
